In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z=(x−μ)/ σ


In [3]:
#1 How many negative numbers are there?
#Answer: 4

In [4]:
a[a<0].shape[0]

4

In [ ]:
#2 How many positive numbers are there?
#Answer: 5

In [5]:
a[a>0].shape[0]

5

In [ ]:
#3 How many even positive numbers are there?
#Answer: 3

In [6]:
b = a[a % 2 ==0]
b.shape[0]
#this gives me all the evens

8

In [8]:
b[b>0]
#this will give me all the of the even positive #s

array([ 4, 10, 12])

In [ ]:
#4 If you were to add 3 to each data point, 
#how many positive numbers would there be?
#Answer: 10

In [7]:
c = a+3
c.shape[0]
#this gives me the addition

12

In [10]:
c[c>0]


array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [ ]:
#5 If you squared each number, 
#what would the new mean and standard deviation be?
#Answer: mean = 74
#Answer: standard deviation = 144.0243035046516

In [31]:
squared= a**2
squared
#this will give me the array squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [32]:
squared.mean()

74.0

In [34]:
standev = squared.std()
standev

144.0243035046516

In [ ]:
#6: A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the mean of the data is 0. 
#This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.

#Answer: array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0., -10.])

In [13]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [13]:
a.mean()

3.0

In [36]:
center_cal= a- (a.mean())
center_cal

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [37]:
#7 Calculate the z-score for each data point. Recall that the z-score is given by:
# Z=(x−μ)/ σ
#Z= d / f
z_cal = (a -squared)/standev
z_cal

array([-0.08331927, -0.62489453, -0.91651198, -3.51329593, -0.04165964,
       -0.01388655,  0.        ,  0.        ,  0.        , -0.29161745,
       -0.04165964, -0.38882327])

In [33]:
#8 MORE NUMPY PRACTICE
#added to seperate file