##MORE NUMPY EXERCISES

In [5]:
import numpy as np

In [3]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
sum_of_a = a.sum()
sum_of_a

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [10]:
min_of_a = a.min()
min_of_a

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [12]:
max_of_a = a.max()
max_of_a

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [14]:
mean_of_a = a.mean()
mean_of_a

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [17]:
product_of_a = np.prod(a)
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [26]:
square_of_a = np.square(a)
square_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [22]:
odds_in_a = a[a % 2 !=0]
odds_in_a

array([1, 3, 5, 7, 9])

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [24]:
evens_in_a = a[a % 2 ==0]
evens_in_a

array([ 2,  4,  6,  8, 10])

 What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
 
 Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [6]:
b = np.array ([
    [3, 4, 5],
    [6, 7, 8]
])

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

#### sum_of_b = 0
#### for row in b:
####    sum_of_b += sum(row)

In [51]:
sum_of_b = b.sum()
sum_of_b

33

In [ ]:
#Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [52]:
min_of_b = b.min()
min_of_b

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [54]:
max_of_b = b.max()
max_of_b

8

In [55]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [56]:
mean_of_b = b.mean()
mean_of_b

5.5

In [57]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number

In [58]:
prod_of_b = np.prod(b)
prod_of_b

20160

In [59]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
#squares_of_b = []
#for row in b:
#    for number in row:
#        squares_of_b.append(number**2)

In [82]:
square_of_b = np.square(b)
square_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [61]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
#odds_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 != 0):
#            odds_in_b.append(number)

In [63]:
odds_in_b = b[b % 2 !=0]
odds_in_b

array([3, 5, 7])

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#evens_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)

In [64]:
evens_in_b = b[b % 2 ==0]
evens_in_b

array([4, 6, 8])

In [65]:
# Exercise 9 - print out the shape of the array b.

In [66]:
print(b.shape)

(2, 3)


In [67]:
# Exercise 10 - transpose the array b.

In [68]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [69]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [71]:
np.reshape(b, (1,6))

array([[3, 4, 5, 6, 7, 8]])

In [72]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [73]:
np.reshape(b, (6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [75]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [76]:
# Exercise 1 - Find the min, max, sum, and product of c.

In [78]:
c.min()

1

In [79]:
c.max()

9

In [80]:
c.sum()

45

In [83]:
np.prod(c)

362880

In [84]:
# Exercise 2 - Determine the standard deviation of c.

In [87]:
np.std(c)

2.581988897471611

In [88]:
# Exercise 3 - Determine the variance of c.

In [89]:
np.var(c)

6.666666666666667

In [90]:
# Exercise 4 - Print out the shape of the array c

In [91]:
print(c.shape)

(3, 3)


In [92]:
# Exercise 5 - Transpose c and print out transposed result.

In [95]:
transposed_results = np.transpose(c)
transposed_results

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
print(transposed_results.shape)

(3, 3)


In [97]:
# Exercise 6 - Get the dot product of the array c with c. 

In [98]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [99]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [107]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [112]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [108]:
# Exercise 1 - Find the sine of all the numbers in d

In [113]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [105]:
# Exercise 2 - Find the cosine of all the numbers in d

In [114]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [115]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [117]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [118]:
d[d<0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [124]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [106]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [ ]:
# Exercise 8 - Print out the shape of d.

In [122]:
print(d.shape)

(3, 6)


In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [129]:
transpose_d = np.transpose(d)
transpose_d

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [130]:
print(transpose_d.shape)

(6, 3)


In [128]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [131]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])