In [1]:
import numpy as np

In [2]:
l = list(range(10_000))

In [3]:
a= np.arange(10_000)

#example of speed

In [4]:
%timeit for x in l: x *2

351 µs ± 2.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit [x * 2 for x in l]

432 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%timeit a * 2

3.94 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
a = np.array([12,42,31, 100])

In [11]:
#indexing
a[1]

42

In [12]:
#a = np.array([12,42,31, 100])
#       index([0, 1, 2,  3])

In [13]:
#slicing a list
#[start index:end] <-- up to but NOT including "end"
a[1:]

array([ 42,  31, 100])

In [14]:
a[:2]

array([12, 42])

In [15]:
a[1:3]

array([42, 31])

In [16]:
a[:-1]

array([12, 42, 31])

In [17]:
a[-2:]

array([ 31, 100])

In [24]:
m[0]

array([0, 1, 2])

In [25]:
a = np.array([12, 24, 19, -6])

In [26]:
a+ 1

array([13, 25, 20, -5])

In [27]:
#broadcasting w/ another array

In [28]:
b= np.array([-2, 1, 2, -1])

In [29]:
a+b

array([10, 25, 21, -7])

In [30]:
a ==b

array([False, False, False, False])

In [31]:
a

array([12, 24, 19, -6])

#INDEXING W/BOOLEAN VECTORS (MASKING)

In [38]:
a =np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [40]:
a == 2

array([False, False,  True, False, False, False, False])

In [42]:
#this will return only the true
a[a==2]

array([2])

In [44]:
a>3

array([False, False, False, False,  True,  True,  True])

In [45]:
a[a>3]
#"a" WHERE "a" is greater then 3

array([4, 5, 6])

In [46]:
#HOW TO RETURN A FALSE INSTEAD OF A TRUE

In [47]:
#OPTION 1 
#flip the operator
a[a<3]

array([0, 1, 2])

In [48]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [52]:
#OPTION 2:
#use the "~" which gives opposites
a[~(a>3)]
#a WHERE a is NOT greater then 3 because of the "~"

array([0, 1, 2, 3])

#NUMPY METHODS


#ARRAY CREATION

In [54]:
np.random.randn(5)
#this pulls 5 random numbers

array([ 1.2647426 , -0.88352298,  0.18332884,  0.21748933, -1.34252491])

In [55]:
np.random.randn(2,2)
#requests a random 2x2 array

array([[-0.05086162,  0.7195155 ],
       [ 0.24804627, -0.34515577]])

In [61]:
np.arange(10, 0, -2)
#from 10 to 0, counting backwards by 2

array([10,  8,  6,  4,  2])

In [70]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [62]:
a= np.array([12, 24, 19, -6])

In [64]:
a.min()

-6

In [65]:
a.max()

24

In [66]:
a.mean()

12.25

In [67]:
a.sum()

49

In [71]:
a= np.array([12, 24, 19, -6])
a.shape
#this will show you the shape of the list

(4,)

In [72]:
m = np.array(([1,2,2], [4,5,6]))

In [73]:
m.shape
#number of lists, number in items in each list

(2, 3)

In [74]:
c = np.array(([1,2,3,4], [5,6,7, 8], [9, 10, 11, 12]))

In [75]:
c.shape

(3, 4)

In [76]:
c.shape[0]
#gives you JUST the number of lists

3

In [2]:
m = ([[1,2,3,4], [5,6,7,8]])

In [4]:
#m.shape[0], m.shape[1], m.size

In [5]:
#REFACTOR:
#change the way that code is scructured without changing what its doing

In [7]:
l = [1,2,3,4,5]

In [8]:
def sum_of_list(l):
    sum = 0
    for element in l:
        sum += element
    return sum

In [10]:
#original way
def sum_of_lost(l):
    return l

In [9]:
#"refactor" way
sum_of_list(l)

15

# VERY IMPORTANT FROM TEACHER:
# MASKS

'# of even positives in a: %d' % a[(a > 0) & (a % 2 == 0)].shape[0]
# another way to do it
positive_mask = a > 0
even_mask = a % 2 == 0
a[positive_mask & even_mask].shape[0]
# Or...
positives = a[a > 0]
positive_evens = positives[positives % 2 == 0]