In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z=(x−μ)/ σ


In [3]:
#1 How many negative numbers are there?
#Answer: 4

In [5]:
a[a<0]

array([-2, -1, -6, -7])

In [ ]:
#2 How many positive numbers are there?
#Answer: 5

In [6]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [ ]:
#3 How many even positive numbers are there?
#Answer: 3

In [7]:
b = a[a % 2 ==0]
b
#this gives me all the evens

array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [8]:
b[b>0]
#this will give me all the of the even positive #s

array([ 4, 10, 12])

In [ ]:
#4 If you were to add 3 to each data point, 
#how many positive numbers would there be?
#Answer: 10

In [9]:
c = a+3
c
#this gives me the addition

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [10]:
c[c>0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [ ]:
#5 If you squared each number, 
#what would the new mean and standard deviation be?
#Answer: mean = 74
#Answer: standard deviation = 144.0243035046516

In [11]:
d= a**2
d
#this will give me the array squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [26]:
d.mean()

74.0

In [19]:
f = d.std()
f

144.0243035046516

In [ ]:
#6: A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the mean of the data is 0. 
#This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.

#Answer: array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0., -10.])

In [13]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [13]:
a.mean()

3.0

In [20]:
e= a- (a.mean())
e

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [22]:
#7 Calculate the z-score for each data point. Recall that the z-score is given by:
# Z=(x−μ)/ σ
#Z= d / f
z = d/f
z

array([0.11109236, 0.69432726, 0.99983125, 3.6729912 , 0.02777309,
       0.00694327, 0.        , 0.        , 0.        , 0.24995781,
       0.06248945, 0.34022036])

In [33]:
#8 MORE NUMPY PRACTICE
#added to seperate file