##MORE NUMPY EXERCISES

In [2]:
import numpy as np

In [3]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [7]:
sum_of_a = a.sum()
sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [10]:
min_of_a = a.min()
min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [12]:
max_of_a = a.max()
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [14]:
mean_of_a = a.mean()
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [17]:
product_of_a = np.prod(a)
product_of_a

3628800

Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [26]:
square_of_a = np.square(a)
square_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [22]:
odds_in_a = a[a % 2 !=0]
odds_in_a

array([1, 3, 5, 7, 9])

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [24]:
evens_in_a = a[a % 2 ==0]
evens_in_a

array([ 2,  4,  6,  8, 10])

 What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
 
 Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [34]:
b = np.array ([
    [3, 4, 5],
    [6, 7, 8]
])

In [ ]:
#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [51]:
sum_of_b = b.sum()
sum_of_b

33

In [ ]:
#Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

In [52]:
min_of_b = b.min()
min_of_b

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [54]:
max_of_b = b.max()
max_of_b

8

In [55]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [56]:
mean_of_b = b.mean()
mean_of_b

5.5

In [57]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number

In [58]:
prod_of_b = np.prod(b)
prod_of_b

20160

In [59]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
#squares_of_b = []
#for row in b:
#    for number in row:
#        squares_of_b.append(number**2)

In [60]:
prod_of_b = np.square(b)
prod_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [61]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
#odds_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 != 0):
#            odds_in_b.append(number)

In [63]:
odds_in_b = b[b % 2 !=0]
odds_in_b

array([3, 5, 7])

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#evens_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)

In [64]:
evens_in_b = b[b % 2 ==0]
evens_in_b

array([4, 6, 8])